package test01.data.user;

import tech.fonrouge.ui.Annotations.AutoGenerated;
import test01.data.person.PersonData;
import java.util.Date;

@AutoGenerated()
public class UserData<T extends User> extends PersonData<T> {

    /**
     * constructor
     */
    @AutoGenerated()
    public UserData(T user) {
        super(user);
    }

    /**
     * getUserId
     */
    @AutoGenerated()
    public String getUserId() {
        return tableState.getFieldValue(table.field_userId, String.class);
    }

    /**
     * getUserLevel
     */
    @AutoGenerated()
    public String getUserLevel() {
        return tableState.getFieldValue(table.field_userLevel, String.class);
    }

    /**
     * getPassword
     */
    @AutoGenerated()
    public String getPassword() {
        return tableState.getFieldValue(table.field_password, String.class);
    }

    /**
     * getLastLogin
     */
    @AutoGenerated()
    public Date getLastLogin() {
        return tableState.getFieldValue(table.field_lastLogin, Date.class);
    }

    /**
     * getLogCounter
     */
    @AutoGenerated()
    public Integer getLogCounter() {
        return tableState.getFieldValue(table.field_logCounter, Integer.class);
    }
}
