package test01.data.user;

import tech.fonrouge.MOODB.Annotations.AutoGenerated;
import test01.data.person.PersonData;

import java.util.Date;

@AutoGenerated()
public class UserData<T extends User> extends PersonData<T> {

    /* @@ begin field descriptor @@ */
    @AutoGenerated()
    public UserData(T user) {
        super(user);
    }

    @AutoGenerated()
    public String getUserId() {
        return tableState.getFieldValue(table.field_userId, String.class);
    }

    @AutoGenerated()
    public String getUserLevel() {
        return tableState.getFieldValue(table.field_userLevel, String.class);
    }

    @AutoGenerated()
    public String getPassword() {
        return tableState.getFieldValue(table.field_password, String.class);
    }

    @AutoGenerated()
    public Date getLastLogin() {
        return tableState.getFieldValue(table.field_lastLogin, Date.class);
    }

    @AutoGenerated()
    public Integer getLogCounter() {
        return tableState.getFieldValue(table.field_logCounter, Integer.class);
    }
}
