package test02.datos;

import org.bson.types.ObjectId;
import tech.fonrouge.ui.Annotations.AutoGenerated;
import tech.fonrouge.MOODB.MFieldDate;
import tech.fonrouge.MOODB.MTable;
import java.util.Date;

@AutoGenerated()
public abstract class Base extends MTable {

    /**
     * field_fechaRegistro
     */
    @AutoGenerated()
    public final MFieldDate field_fechaRegistro = new MFieldDate(this, "fechaRegistro") {
        @Override
        protected void initialize() {
            calculated = true;
            calcValue = () -> calcField_fechaRegistro();
        }
    };

    /**
     * field_fecha
     */
    @AutoGenerated()
    public final MFieldDate field_fecha = new MFieldDate(this, "fecha") {
        @Override
        protected void initialize() {
        }
    };

    /**
     * getMDatabaseClass
     */
    @Override
    @AutoGenerated()
    public Class getMDatabaseClass() {
        return Test2Database.class;
    }

    /* @@ end field descriptor @@ */
    /**
     * calcField_fechaRegistro
     */
    @AutoGenerated()
    private Date calcField_fechaRegistro() {
        Object o = field__id.value();
        if (o instanceof ObjectId) {
            return ((ObjectId) o).getDate();
        }
        return null;
    }
}
