package test02.datos;

import tech.fonrouge.MOODB.Annotations.AutoGenerated;
import tech.fonrouge.MOODB.MBaseData;

import java.util.Date;

@AutoGenerated()
public abstract class BaseData<T extends Base> extends MBaseData<T> {

    /* @@ begin field descriptor @@ */
    @AutoGenerated()
    public BaseData(T base) {
        super(base);
    }

    @AutoGenerated()
    public Date getFechaRegistro() {
        return tableState.getFieldValue(table.field_fechaRegistro, Date.class);
    }

    @AutoGenerated()
    public Date getFecha() {
        return tableState.getFieldValue(table.field_fecha, Date.class);
    }
}
