package test02.datos;

import tech.fonrouge.ui.Annotations.AutoGenerated;
import tech.fonrouge.MOODB.MBaseData;
import java.util.Date;

@AutoGenerated()
public abstract class BaseData<T extends Base> extends MBaseData<T> {

    /**
     * constructor
     */
    @AutoGenerated()
    public BaseData(T base) {
        super(base);
    }

    /**
     * getFechaRegistro
     */
    @AutoGenerated()
    public Date getFechaRegistro() {
        return tableState.getFieldValue(table.field_fechaRegistro, Date.class);
    }

    /**
     * getFecha
     */
    @AutoGenerated()
    public Date getFecha() {
        return tableState.getFieldValue(table.field_fecha, Date.class);
    }
}
