package test02.datos;

import tech.fonrouge.MOODB.Annotations.AutoGenerated;

@AutoGenerated()
public class InventarioData<T extends Inventario> extends BaseData<T> {

    /* @@ begin field descriptor @@ */
    @AutoGenerated()
    public InventarioData(T inventario) {
        super(inventario);
    }

    @AutoGenerated()
    public String getNombre() {
        return tableState.getFieldValue(table.field_nombre, String.class);
    }

    @AutoGenerated()
    public String getUdem() {
        return tableState.getFieldValue(table.field_udem, String.class);
    }

    @AutoGenerated()
    public String getTipo() {
        return tableState.getFieldValue(table.field_tipo, String.class);
    }

    @AutoGenerated()
    public Integer getLevel() {
        return tableState.getFieldValue(table.field_level, Integer.class);
    }

    @AutoGenerated()
    public Double getExistencia() {
        return tableState.getFieldValue(table.field_existencia, Double.class);
    }

    @AutoGenerated()
    public String getStatus() {
        return tableState.getFieldValue(table.field_status, String.class);
    }
}
