package test02.datos;

import tech.fonrouge.ui.Annotations.AutoGenerated;

@AutoGenerated()
public class InventarioData<T extends Inventario> extends BaseData<T> {

    /**
     * constructor
     */
    @AutoGenerated()
    public InventarioData(T inventario) {
        super(inventario);
    }

    /**
     * getNombre
     */
    @AutoGenerated()
    public String getNombre() {
        return tableState.getFieldValue(table.field_nombre, String.class);
    }

    /**
     * getUdem
     */
    @AutoGenerated()
    public String getUdem() {
        return tableState.getFieldValue(table.field_udem, String.class);
    }

    /**
     * getTipo
     */
    @AutoGenerated()
    public String getTipo() {
        return tableState.getFieldValue(table.field_tipo, String.class);
    }

    /**
     * getLevel
     */
    @AutoGenerated()
    public Integer getLevel() {
        return tableState.getFieldValue(table.field_level, Integer.class);
    }

    /**
     * getExistencia
     */
    @AutoGenerated()
    public Double getExistencia() {
        return tableState.getFieldValue(table.field_existencia, Double.class);
    }

    /**
     * getStatus
     */
    @AutoGenerated()
    public String getStatus() {
        return tableState.getFieldValue(table.field_status, String.class);
    }
}
