package test01.data.person;

import tech.fonrouge.MOODB.Annotations.AutoGenerated;
import test01.data.tableBase.TableBaseData;

import java.util.Date;

@AutoGenerated()
public abstract class PersonData<T extends Person> extends TableBaseData<T> {

    /* @@ begin field descriptor @@ */
    @AutoGenerated()
    public PersonData(T person) {
        super(person);
    }

    @AutoGenerated()
    public String getName() {
        return tableState.getFieldValue(table.field_name, String.class);
    }

    @AutoGenerated()
    public String getFirstName() {
        return tableState.getFieldValue(table.field_firstName, String.class);
    }

    @AutoGenerated()
    public String getLastName() {
        return tableState.getFieldValue(table.field_lastName, String.class);
    }

    @AutoGenerated()
    public Date getBday() {
        return tableState.getFieldValue(table.field_bday, Date.class);
    }

    @AutoGenerated()
    public String getGender() {
        return tableState.getFieldValue(table.field_gender, String.class);
    }

    @AutoGenerated()
    public Boolean getMarried() {
        return tableState.getFieldValue(table.field_married, Boolean.class);
    }

    @AutoGenerated()
    public String getPersonId() {
        return tableState.getFieldValue(table.field_personId, String.class);
    }
}
