package test01.data.person;

import tech.fonrouge.ui.Annotations.AutoGenerated;
import test01.data.tableBase.TableBaseData;
import java.util.Date;

@AutoGenerated()
public abstract class PersonData<T extends Person> extends TableBaseData<T> {

    /**
     * constructor
     */
    @AutoGenerated()
    public PersonData(T person) {
        super(person);
    }

    /**
     * getName
     */
    @AutoGenerated()
    public String getName() {
        return tableState.getFieldValue(table.field_name, String.class);
    }

    /**
     * getFirstName
     */
    @AutoGenerated()
    public String getFirstName() {
        return tableState.getFieldValue(table.field_firstName, String.class);
    }

    /**
     * getLastName
     */
    @AutoGenerated()
    public String getLastName() {
        return tableState.getFieldValue(table.field_lastName, String.class);
    }

    /**
     * getBday
     */
    @AutoGenerated()
    public Date getBday() {
        return tableState.getFieldValue(table.field_bday, Date.class);
    }

    /**
     * getGender
     */
    @AutoGenerated()
    public String getGender() {
        return tableState.getFieldValue(table.field_gender, String.class);
    }

    /**
     * getMarried
     */
    @AutoGenerated()
    public Boolean getMarried() {
        return tableState.getFieldValue(table.field_married, Boolean.class);
    }

    /**
     * getPersonId
     */
    @AutoGenerated()
    public String getPersonId() {
        return tableState.getFieldValue(table.field_personId, String.class);
    }
}
