package test01.data.person;

import tech.fonrouge.MOODB.Annotations.AutoGenerated;
import tech.fonrouge.MOODB.*;
import test01.data.tableBase.TableBase;

@AutoGenerated()
public abstract class Person extends TableBase {

    @AutoGenerated()
    public final MFieldString field_name = new MFieldString(this, "name") {
        @Override
        protected void initialize() {
            notNull = true;
            description = "Name";
        }
    };

    @AutoGenerated()
    public final MFieldString field_firstName = new MFieldString(this, "firstName") {
        @Override
        protected void initialize() {
            notNull = true;
            description = "First name";
        }
    };

    @AutoGenerated()
    public final MFieldString field_lastName = new MFieldString(this, "lastName") {
        @Override
        protected void initialize() {
            description = "Last name";
        }
    };

    @AutoGenerated()
    public final MFieldDate field_bday = new MFieldDate(this, "bday") {
        @Override
        protected void initialize() {
            description = "Birth day";
        }
    };

    @AutoGenerated()
    public final MFieldString field_gender = new MFieldString(this, "gender") {
        @Override
        protected void initialize() {
            notNull = true;

            valueItems = new ValueItems<>();
            valueItems.put("?", "Undetermined");
            valueItems.put("M", "Male");
            valueItems.put("F", "Female");
        }
    };

    @AutoGenerated()
    public final MFieldBoolean field_married = new MFieldBoolean(this, "married") {
        @Override
        protected void initialize() {
        }
    };

    @AutoGenerated()
    public final MFieldString field_personId = new MFieldString(this, "personId") {
        @Override
        protected void initialize() {
            description = "Person Id";
        }
    };

    @AutoGenerated()
    public final MIndex index_personId = new MIndex(this, "personId", "", "personId", true, false) {
        @Override
        protected void initialize() {
        }
    };
}
