package test01.data.tableBase;

import tech.fonrouge.MOODB.MTable;
import test01.data.TestDatabase;

public abstract class TableBase extends MTable {

    @Override
    @AutoGenerated()
    public Class getMDatabaseClass() {
        return TestDatabase.class;
    }
}
