package test01.data.tableBase;

import tech.fonrouge.MOODB.Annotations.AutoGenerated;
import tech.fonrouge.MOODB.MBaseData;

@AutoGenerated()
public abstract class TableBaseData<T extends TableBase> extends MBaseData<T> {

    @AutoGenerated()
    public TableBaseData(T tablebase) {
        super(tablebase);
    }
}
