package test01.data.invoiceItem.xInvoice;

import tech.fonrouge.MOODB.MIndex;
import test01.data.invoice.Invoice;
import test01.data.invoiceItem.InvoiceItem;

public class InvoiceItem_xInvoice extends InvoiceItem {

    @AutoGenerated()
    public final MIndex index_invoice_invItem = new MIndex(this, "invoice_invItem", "invoice", "invItem", true, false) {
        @Override
        protected void initialize() {
        }
    };

    @AutoGenerated()
    public InvoiceItem_xInvoice(Invoice masterSource) {
        setMasterSource(masterSource, field_invoice);
    }

    @AutoGenerated()
    public Invoice getMasterSource() {
        return (Invoice) super.getMasterSource();
    }

    @AutoGenerated()
    @Override()
    public InvoiceItem_xInvoiceData getData() {
        return new InvoiceItem_xInvoiceData<>(this);
    }
}
