package test01.data.invoiceItem.xInvoice;

import tech.fonrouge.MOODB.Annotations.AutoGenerated;
import test01.data.invoiceItem.InvoiceItemData;

@AutoGenerated()
public class InvoiceItem_xInvoiceData<T extends InvoiceItem_xInvoice> extends InvoiceItemData<T> {

    /* @@ begin field descriptor @@ */
    @AutoGenerated()
    public InvoiceItem_xInvoiceData(T invoiceitem_xinvoice) {
        super(invoiceitem_xinvoice);
    }
}
