package test01.data.invoiceItem.xInvoice;

import tech.fonrouge.MOODB.Annotations.AutoGenerated;
import tech.fonrouge.MOODB.MIndex;
import test01.data.invoice.Invoice;
import test01.data.invoiceItem.InvoiceItem;

@AutoGenerated()
public class InvoiceItem_xInvoice extends InvoiceItem {

    /**
     * index_invoice_invItem
     */
    @AutoGenerated()
    public final MIndex index_invoice_invItem = new MIndex(this, "invoice_invItem", "invoice", "invItem", true, false, null, null) {
        @Override
        protected void initialize() {
        }
    };

    /**
     * constructor with masterSource parameter
     */
    @AutoGenerated()
    public InvoiceItem_xInvoice(Invoice masterSource) {
        setMasterSource(masterSource, field_invoice);
    }

    /**
     * getMasterSource
     */
    @AutoGenerated()
    public Invoice getMasterSource() {
        return (Invoice) super.getMasterSource();
    }

    /**
     * getData
     */
    @Override()
    @AutoGenerated()
    public InvoiceItem_xInvoiceData getData() {
        return new InvoiceItem_xInvoiceData<>(this);
    }
}
