package test01.data.invoiceItem.xInvoice;

import tech.fonrouge.ui.Annotations.AutoGenerated;
import test01.data.invoiceItem.InvoiceItemData;

@AutoGenerated()
public class InvoiceItem_xInvoiceData<T extends InvoiceItem_xInvoice> extends InvoiceItemData<T> {

    /**
     * constructor
     */
    @AutoGenerated()
    public InvoiceItem_xInvoiceData(T invoiceItem_xInvoice) {
        super(invoiceItem_xInvoice);
    }
}
