package test01.data.customer;

import tech.fonrouge.MOODB.Annotations.AutoGenerated;
import test01.data.entity.EntityData;

@AutoGenerated()
public class CustomerData<T extends Customer> extends EntityData<T> {

    /* @@ begin field descriptor @@ */
    @AutoGenerated()
    public CustomerData(T customer) {
        super(customer);
    }

    @AutoGenerated()
    public String getCustomerId() {
        return tableState.getFieldValue(table.field_customerId, String.class);
    }
}
