package test01.data.customer;

import tech.fonrouge.MOODB.Annotations.AutoGenerated;
import tech.fonrouge.MOODB.MFieldString;
import tech.fonrouge.MOODB.MIndex;
import test01.data.entity.Entity;

@AutoGenerated()
public class Customer extends Entity {

    /* @@ begin field descriptor @@ */
    @AutoGenerated()
    public final MFieldString field_customerId = new MFieldString(this, "customerId") {
        @Override
        protected void initialize() {
            description = "Customer Id";
        }
    };

    @AutoGenerated()
    public final MIndex index_customerId = new MIndex(this, "customerId", "", "customerId", true, false) {
        @Override
        protected void initialize() {
        }
    };

    @Override
    @AutoGenerated()
    public final String getTableName() {
        return "customer";
    }

    @Override
    @AutoGenerated()
    public CustomerData getData() {
        return new CustomerData<>(this);
    }
}
