package tech.fonrouge.ui;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

public class Annotations {
    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.FIELD)
    public @interface AssignWith {
        String parentNode();
        String selectorId();
    }

    @Retention(RetentionPolicy.RUNTIME)
    public @interface AutoGenerated {

    }

    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.FIELD)
    @SuppressWarnings("WeakerAccess")
    public @interface BindCtrlList {

    }

    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.TYPE)
    @SuppressWarnings("WeakerAccess")
    public @interface NoAutoBinding {

    }

    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.FIELD)
    @SuppressWarnings("WeakerAccess")
    public @interface NoBindNode {

    }

    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.FIELD)
    public @interface BindField {
        String fieldName();
    }
}
