package test01.data.invoice;

import tech.fonrouge.MOODB.*;
import test01.data.customer.Customer;
import test01.data.tableBase.TableBase;

public class Invoice extends TableBase {

    @AutoGenerated()
    public final MFieldInteger field_docNumber = new MFieldInteger(this, "docNumber") {
        @Override
        protected void initialize() {
            autoInc = true;
            required = true;
            description = "Invoice number";
        }
    };

    @AutoGenerated()
    public final MFieldTableField<Customer> field_customer = new MFieldTableField<Customer>(this, "customer") {
        @Override
        protected void initialize() {
            required = true;
        }

        @Override
        protected Customer buildTableField() {
            return new Customer();
        }
    };

    @AutoGenerated()
    public final MFieldDate field_date = new MFieldDate(this, "date") {
        @Override
        protected void initialize() {
            required = true;
        }
    };

    @AutoGenerated()
    public final MFieldInteger field_daysOfCredit = new MFieldInteger(this, "daysOfCredit") {
        @Override
        protected void initialize() {
            required = true;
        }
    };

    @AutoGenerated()
    public final MFieldLong field_itemsCount = new MFieldLong(this, "itemsCount") {
        @Override
        protected void initialize() {
            calculated = true;
            calcValue = () -> calcField_itemsCount();
        }
    };

    @AutoGenerated()
    public final MFieldBoolean field_reqShipment = new MFieldBoolean(this, "reqShipment") {
        @Override
        protected void initialize() {
            required = true;
        }
    };

    @AutoGenerated()
    public final MIndex index_docNumber = new MIndex(this, "docNumber", "", "docNumber", true, false) {
        @Override
        protected void initialize() {
        }
    };

    @AutoGenerated()
    @Override()
    public final String getTableName() {
        return "invoice";
    }

    @AutoGenerated()
    @Override()
    public InvoiceData getData() {
        return new InvoiceData<>(this);
    }

    @AutoGenerated()
    private Long calcField_itemsCount() {
        return null;
    }
}
