package test01.data.invoice;

import tech.fonrouge.MOODB.*;
import tech.fonrouge.ui.Annotations.AutoGenerated;
import test01.data.customer.Customer;
import test01.data.tableBase.TableBase;

@AutoGenerated()
public class Invoice extends TableBase {

    /**
     * field_date
     */
    @AutoGenerated()
    public final MFieldDate field_date = new MFieldDate(this, "date") {
        @Override
        protected void initialize() {
            notNull = true;
        }
    };

    /**
     * field_daysOfCredit
     */
    @AutoGenerated()
    public final MFieldInteger field_daysOfCredit = new MFieldInteger(this, "daysOfCredit") {
        @Override
        protected void initialize() {
            notNull = true;
        }
    };

    /**
     * field_itemsCount
     */
    @AutoGenerated()
    public final MFieldLong field_itemsCount = new MFieldLong(this, "itemsCount") {
        @Override
        protected void initialize() {
            calculated = true;
            calcValue = () -> calcField_itemsCount();
        }
    };

    /**
     * field_reqShipment
     */
    @AutoGenerated()
    public final MFieldBoolean field_reqShipment = new MFieldBoolean(this, "reqShipment") {
        @Override
        protected void initialize() {
            notNull = true;
        }
    };

    /**
     * index_docNumber
     */
    @AutoGenerated()
    public final MIndex index_docNumber = new MIndex(this, "docNumber", "", "docNumber", true, false, null, null) {
        @Override
        protected void initialize() {
        }
    };

    /**
     * field_docNumber
     */
    @AutoGenerated()
    public final MFieldInteger field_docNumber = new MFieldInteger(this, "docNumber") {
        @Override
        protected void initialize() {
            autoInc = true;
            description = "Invoice number";
        }
    };

    /**
     * field_customer
     */
    @AutoGenerated()
    public final MFieldTableField<Customer> field_customer = new MFieldTableField<Customer>(this, "customer") {
        @Override
        protected void initialize() {
            notNull = true;
        }

        @Override
        protected Class<Customer> getTableClass() {
            return Customer.class;
        }
    };
    /**
     * field_deliveryCost
     */
    @AutoGenerated()
    public final MFieldDouble field_deliveryCost = new MFieldDouble(this, "deliveryCost") {
        @Override
        protected void initialize() {
            notNull = true;
        }
    };

    /**
     * getTableName
     */
    @Override()
    @AutoGenerated()
    public final String getTableName() {
        return "invoice";
    }

    /**
     * calcField_itemsCount
     */
    @AutoGenerated()
    private Long calcField_itemsCount() {
        return null;
    }

    /**
     * getData
     */
    @Override()
    @AutoGenerated()
    public InvoiceData getData() {
        return new InvoiceData<>(this);
    }
}
