package test01.data.invoice;

import org.bson.types.ObjectId;
import tech.fonrouge.MOODB.MTable.AutoGenerated;
import test01.data.tableBase.TableBaseData;

import java.util.Date;

public class InvoiceData<T extends Invoice> extends TableBaseData<T> {

    protected Integer counter = 0;

    @AutoGenerated()
    public InvoiceData(T invoice) {
        super(invoice);
    }

    @AutoGenerated()
    public Integer getDocNumber() {
        return tableState.getFieldValue(table.field_docNumber, Integer.class);
    }

    @AutoGenerated()
    public ObjectId getCustomer() {
        return tableState.getFieldValue(table.field_customer, ObjectId.class);
    }

    @AutoGenerated()
    public Date getDate() {
        return tableState.getFieldValue(table.field_date, Date.class);
    }

    @AutoGenerated()
    public Integer getDaysOfCredit() {
        return tableState.getFieldValue(table.field_daysOfCredit, Integer.class);
    }

    @AutoGenerated()
    public Long getItemsCount() {
        return tableState.getFieldValue(table.field_itemsCount, Long.class);
    }

    @AutoGenerated()
    public Boolean getReqShipment() {
        return tableState.getFieldValue(table.field_reqShipment, Boolean.class);
    }
}
