package test01.data.invoiceItem;

import tech.fonrouge.MOODB.Annotations.AutoGenerated;
import tech.fonrouge.MOODB.MFieldDouble;
import tech.fonrouge.MOODB.MFieldTableField;
import tech.fonrouge.MOODB.MIndex;
import test01.data.inventoryItem.InventoryItem;
import test01.data.invoice.Invoice;
import test01.data.tableBase.TableBase;
import tech.fonrouge.MOODB.*;

@AutoGenerated()
public class InvoiceItem extends TableBase {

    /**
     * field_invoice
     */
    @AutoGenerated()
    public final MFieldTableField<Invoice> field_invoice = new MFieldTableField<Invoice>(this, "invoice") {
        @Override
        protected void initialize() {
            description = "Invoice";
        }

        @Override
        protected Class<Invoice> getTableClass() {
            return Invoice.class;
        }
    };

    /**
     * field_invItem
     */
    @AutoGenerated()
    public final MFieldTableField<InventoryItem> field_invItem = new MFieldTableField<InventoryItem>(this, "invItem") {
        @Override
        protected void initialize() {
        }

        @Override
        protected Class<InventoryItem> getTableClass() {
            return InventoryItem.class;
        }
    };

    /**
     * field_qty
     */
    @AutoGenerated()
    public final MFieldDouble field_qty = new MFieldDouble(this, "qty") {
        @Override
        protected void initialize() {
            description = "Quantity";
        }
    };

    /**
     * field_unitPrice
     */
    @AutoGenerated()
    public final MFieldDouble field_unitPrice = new MFieldDouble(this, "unitPrice") {
        @Override
        protected void initialize() {
            description = "Unit Price";
        }
    };

    /**
     * field_total
     */
    @AutoGenerated()
    public final MFieldDouble field_total = new MFieldDouble(this, "total") {
        @Override
        protected void initialize() {
            calculated = true;
            calcValue = () -> calcField_total();
        }
    };

    /**
     * index_date
     */
    @AutoGenerated()
    public final MIndex index_date = new MIndex(this, "date", "", "date", false, false, null, null) {
        @Override
        protected void initialize() {
        }
    };

    /**
     * getTableName
     */
    @Override
    @AutoGenerated()
    public final String getTableName() {
        return "invoiceItem";
    }

    /**
     * getData
     */
    @Override
    @AutoGenerated()
    public InvoiceItemData getData() {
        return new InvoiceItemData<>(this);
    }

    /**
     * calcField_total
     */
    @AutoGenerated()
    private Double calcField_total() {
        return null;
    }
}
