package test01.data.invoiceItem;

import org.bson.types.ObjectId;
import tech.fonrouge.ui.Annotations.AutoGenerated;
import test01.data.tableBase.TableBaseData;

@AutoGenerated()
public class InvoiceItemData<T extends InvoiceItem> extends TableBaseData<T> {

    /**
     * constructor
     */
    @AutoGenerated()
    public InvoiceItemData(T invoiceItem) {
        super(invoiceItem);
    }

    /**
     * getInvoice
     */
    @AutoGenerated()
    public ObjectId getInvoice() {
        return tableState.getFieldValue(table.field_invoice, ObjectId.class);
    }

    /**
     * getInvItem
     */
    @AutoGenerated()
    public ObjectId getInvItem() {
        return tableState.getFieldValue(table.field_invItem, ObjectId.class);
    }

    /**
     * getQty
     */
    @AutoGenerated()
    public Double getQty() {
        return tableState.getFieldValue(table.field_qty, Double.class);
    }

    /**
     * getUnitPrice
     */
    @AutoGenerated()
    public Double getUnitPrice() {
        return tableState.getFieldValue(table.field_unitPrice, Double.class);
    }

    /**
     * getTotal
     */
    @AutoGenerated()
    public Double getTotal() {
        return tableState.getFieldValue(table.field_total, Double.class);
    }
}
