package test01.data.invoiceItem;

import tech.fonrouge.MOODB.Annotations.AutoGenerated;
import tech.fonrouge.MOODB.MFieldDouble;
import tech.fonrouge.MOODB.MFieldTableField;
import tech.fonrouge.MOODB.MIndex;
import test01.data.inventoryItem.InventoryItem;
import test01.data.invoice.Invoice;
import test01.data.tableBase.TableBase;

@AutoGenerated()
public class InvoiceItem extends TableBase {

    @AutoGenerated()
    public final MFieldTableField<Invoice> field_invoice = new MFieldTableField<Invoice>(this, "invoice") {
        @Override
        protected void initialize() {
            notNull = true;
            description = "Invoice";
        }

        @Override
        protected Invoice buildTableField() {
            return new Invoice();
        }
    };

    @AutoGenerated()
    public final MFieldTableField<InventoryItem> field_invItem = new MFieldTableField<InventoryItem>(this, "invItem") {
        @Override
        protected void initialize() {
            notNull = true;
        }

        @Override
        protected InventoryItem buildTableField() {
            return new InventoryItem();
        }
    };

    @AutoGenerated()
    public final MFieldDouble field_qty = new MFieldDouble(this, "qty") {
        @Override
        protected void initialize() {
            notNull = true;
            description = "Quantity";
        }
    };

    @AutoGenerated()
    public final MFieldDouble field_unitPrice = new MFieldDouble(this, "unitPrice") {
        @Override
        protected void initialize() {
            notNull = true;
            description = "Unit Price";
        }
    };

    @AutoGenerated()
    public final MFieldDouble field_total = new MFieldDouble(this, "total") {
        @Override
        protected void initialize() {
            calculated = true;
            calcValue = () -> calcField_total();
        }
    };

    @AutoGenerated()
    public final MIndex index_date = new MIndex(this, "date", "", "date", false, false) {
        @Override
        protected void initialize() {
        }
    };

    @Override
    @AutoGenerated()
    public final String getTableName() {
        return "invoiceItem";
    }

    @Override
    @AutoGenerated()
    public InvoiceItemData getData() {
        return new InvoiceItemData<>(this);
    }

    @AutoGenerated()
    private Double calcField_total() {
        return null;
    }
}
