package test01.data.inventoryItem;

import org.bson.types.Binary;
import tech.fonrouge.MOODB.Annotations.AutoGenerated;
import test01.data.tableBase.TableBaseData;

import java.util.Date;

@AutoGenerated()
public class InventoryItemData<T extends InventoryItem> extends TableBaseData<T> {

    /* @@ begin field descriptor @@ */
    @AutoGenerated()
    public InventoryItemData(T inventoryitem) {
        super(inventoryitem);
    }

    @AutoGenerated()
    public String getItemId() {
        return tableState.getFieldValue(table.field_itemId, String.class);
    }

    @AutoGenerated()
    public String getName() {
        return tableState.getFieldValue(table.field_name, String.class);
    }

    @AutoGenerated()
    public String getUom() {
        return tableState.getFieldValue(table.field_uom, String.class);
    }

    @AutoGenerated()
    public Double getStock() {
        return tableState.getFieldValue(table.field_stock, Double.class);
    }

    @AutoGenerated()
    public Double getUnitPrice() {
        return tableState.getFieldValue(table.field_unitPrice, Double.class);
    }

    @AutoGenerated()
    public Date getDate() {
        return tableState.getFieldValue(table.field_date, Date.class);
    }

    @AutoGenerated()
    public Binary getImage() {
        return tableState.getFieldValue(table.field_image, Binary.class);
    }

    @AutoGenerated()
    public String getType() {
        return tableState.getFieldValue(table.field_type, String.class);
    }

    @AutoGenerated()
    public Boolean getTaxable() {
        return tableState.getFieldValue(table.field_taxable, Boolean.class);
    }
}
