package test01.data.inventoryItem;

import org.bson.types.Binary;
import tech.fonrouge.ui.Annotations.AutoGenerated;
import test01.data.tableBase.TableBaseData;
import java.util.Date;

@AutoGenerated()
public class InventoryItemData<T extends InventoryItem> extends TableBaseData<T> {

    /**
     * constructor
     */
    @AutoGenerated()
    public InventoryItemData(T inventoryItem) {
        super(inventoryItem);
    }

    /**
     * getItemId
     */
    @AutoGenerated()
    public String getItemId() {
        return tableState.getFieldValue(table.field_itemId, String.class);
    }

    /**
     * getName
     */
    @AutoGenerated()
    public String getName() {
        return tableState.getFieldValue(table.field_name, String.class);
    }

    /**
     * getUom
     */
    @AutoGenerated()
    public String getUom() {
        return tableState.getFieldValue(table.field_uom, String.class);
    }

    /**
     * getStock
     */
    @AutoGenerated()
    public Double getStock() {
        return tableState.getFieldValue(table.field_stock, Double.class);
    }

    /**
     * getUnitPrice
     */
    @AutoGenerated()
    public Double getUnitPrice() {
        return tableState.getFieldValue(table.field_unitPrice, Double.class);
    }

    /**
     * getDate
     */
    @AutoGenerated()
    public Date getDate() {
        return tableState.getFieldValue(table.field_date, Date.class);
    }

    /**
     * getImage
     */
    @AutoGenerated()
    public Binary getImage() {
        return tableState.getFieldValue(table.field_image, Binary.class);
    }

    /**
     * getType
     */
    @AutoGenerated()
    public String getType() {
        return tableState.getFieldValue(table.field_type, String.class);
    }

    /**
     * getTaxable
     */
    @AutoGenerated()
    public Boolean getTaxable() {
        return tableState.getFieldValue(table.field_taxable, Boolean.class);
    }
}
