package test01.data.inventoryItem;

import tech.fonrouge.MOODB.Annotations.AutoGenerated;
import tech.fonrouge.MOODB.*;
import test01.data.tableBase.TableBase;
import java.util.Date;

@AutoGenerated()
public class InventoryItem extends TableBase {

    /**
     * field_itemId
     */
    @AutoGenerated()
    public final MFieldString field_itemId = new MFieldString(this, "itemId") {
        @Override
        protected void initialize() {
            description = "Inventory Item Id";
        }
    };

    /**
     * field_name
     */
    @AutoGenerated()
    public final MFieldString field_name = new MFieldString(this, "name") {
        @Override
        protected void initialize() {
            description = "name";
        }
    };

    /**
     * field_uom
     */
    @AutoGenerated()
    public final MFieldString field_uom = new MFieldString(this, "uom") {
        @Override
        protected void initialize() {
            description = "Unit of measure";
        }
    };

    /**
     * field_stock
     */
    @AutoGenerated()
    public final MFieldDouble field_stock = new MFieldDouble(this, "stock") {
        @Override
        protected void initialize() {
            description = "Stock";
        }
    };

    /**
     * field_unitPrice
     */
    @AutoGenerated()
    public final MFieldDouble field_unitPrice = new MFieldDouble(this, "unitPrice") {
        @Override
        protected void initialize() {
            description = "Unit price";
        }
    };

    /**
     * field_date
     */
    @AutoGenerated()
    public final MFieldDate field_date = new MFieldDate(this, "date") {
        @Override
        protected void initialize() {
            calculated = true;
            calcValue = () -> calcField_date();
        }
    };

    /**
     * field_image
     */
    @AutoGenerated()
    public final MFieldBinary field_image = new MFieldBinary(this, "image") {
        @Override
        protected void initialize() {
        }
    };

    /**
     * field_type
     */
    @AutoGenerated()
    public final MFieldString field_type = new MFieldString(this, "type") {
        @Override
        protected void initialize() {

            valueItems = new ValueItems<>();
            valueItems.put("ITEM", "Item");
            valueItems.put("SERVICE", "Service");
        }
    };

    /**
     * field_taxable
     */
    @AutoGenerated()
    public final MFieldBoolean field_taxable = new MFieldBoolean(this, "taxable") {
        @Override
        protected void initialize() {
        }
    };

    /**
     * index_itemId
     */
    @AutoGenerated()
    public final MIndex index_itemId = new MIndex(this, "itemId", "", "itemId", true, false, null, null) {
        @Override
        protected void initialize() {
        }
    };

    /**
     * index_name
     */
    @AutoGenerated()
    public final MIndex index_name = new MIndex(this, "name", "", "name", false, false, null, null) {
        @Override
        protected void initialize() {
        }
    };

    /**
     * getTableName
     */
    @Override
    @AutoGenerated()
    public final String getTableName() {
        return "inventoryItem";
    }

    /**
     * getData
     */
    @Override
    @AutoGenerated()
    public InventoryItemData getData() {
        return new InventoryItemData<>(this);
    }

    /**
     * calcField_date
     */
    @AutoGenerated()
    private Date calcField_date() {
        return null;
    }
}
