package test01.data.entity;

import tech.fonrouge.MOODB.Annotations.AutoGenerated;
import tech.fonrouge.MOODB.MFieldString;
import tech.fonrouge.MOODB.MIndex;
import test01.data.tableBase.TableBase;

@AutoGenerated()
public abstract class Entity extends TableBase {

    /* @@ begin field descriptor @@ */
    @AutoGenerated
    public final MFieldString field_name = new MFieldString(this, "name") {
        @Override
        protected void initialize() {
            required = true;
            description = "Name";
        }
    };

    @AutoGenerated
    public final MFieldString field_taxId = new MFieldString(this, "taxId") {
        @Override
        protected void initialize() {
            required = true;
            description = "Tax payer id";
        }
    };

    @AutoGenerated
    public final MFieldString field_country = new MFieldString(this, "country") {
        @Override
        protected void initialize() {
            description = "Country id";
        }
    };

    @AutoGenerated
    public final MFieldString field_address = new MFieldString(this, "address") {
        @Override
        protected void initialize() {
        }
    };

    @AutoGenerated
    public final MFieldString field_phone1 = new MFieldString(this, "phone1") {
        @Override
        protected void initialize() {
        }
    };

    @AutoGenerated
    public final MFieldString field_phone2 = new MFieldString(this, "phone2") {
        @Override
        protected void initialize() {
        }
    };

    @AutoGenerated
    public final MFieldString field_phone3 = new MFieldString(this, "phone3") {
        @Override
        protected void initialize() {
        }
    };

    @AutoGenerated
    public final MFieldString field_webPage = new MFieldString(this, "webPage") {
        @Override
        protected void initialize() {
        }
    };

    @AutoGenerated
    public final MFieldString field_email1 = new MFieldString(this, "email1") {
        @Override
        protected void initialize() {
        }
    };

    @AutoGenerated
    public final MFieldString field_email2 = new MFieldString(this, "email2") {
        @Override
        protected void initialize() {
        }
    };

    @AutoGenerated
    public final MFieldString field_email3 = new MFieldString(this, "email3") {
        @Override
        protected void initialize() {
        }
    };

    @AutoGenerated
    public final MIndex index_taxId = new MIndex(this, "taxId", "", "taxId", true, false) {
        @Override
        protected void initialize() {
        }
    };

    /* @@ end field descriptor @@ */
    protected final Integer counter = 1;
}
