package test01.data.entity;

import tech.fonrouge.ui.Annotations.AutoGenerated;
import test01.data.tableBase.TableBaseData;

@AutoGenerated()
public abstract class EntityData<T extends Entity> extends TableBaseData<T> {

    /**
     * constructor
     */
    @AutoGenerated()
    public EntityData(T entity) {
        super(entity);
    }

    /**
     * getName
     */
    @AutoGenerated()
    public String getName() {
        return tableState.getFieldValue(table.field_name, String.class);
    }

    /**
     * getTaxId
     */
    @AutoGenerated()
    public String getTaxId() {
        return tableState.getFieldValue(table.field_taxId, String.class);
    }

    /**
     * getCountry
     */
    @AutoGenerated()
    public String getCountry() {
        return tableState.getFieldValue(table.field_country, String.class);
    }

    /**
     * getAddress
     */
    @AutoGenerated()
    public String getAddress() {
        return tableState.getFieldValue(table.field_address, String.class);
    }

    /**
     * getPhone1
     */
    @AutoGenerated()
    public String getPhone1() {
        return tableState.getFieldValue(table.field_phone1, String.class);
    }

    /**
     * getPhone2
     */
    @AutoGenerated()
    public String getPhone2() {
        return tableState.getFieldValue(table.field_phone2, String.class);
    }

    /**
     * getPhone3
     */
    @AutoGenerated()
    public String getPhone3() {
        return tableState.getFieldValue(table.field_phone3, String.class);
    }

    /**
     * getWebPage
     */
    @AutoGenerated()
    public String getWebPage() {
        return tableState.getFieldValue(table.field_webPage, String.class);
    }

    /**
     * getEmail1
     */
    @AutoGenerated()
    public String getEmail1() {
        return tableState.getFieldValue(table.field_email1, String.class);
    }

    /**
     * getEmail2
     */
    @AutoGenerated()
    public String getEmail2() {
        return tableState.getFieldValue(table.field_email2, String.class);
    }

    /**
     * getEmail3
     */
    @AutoGenerated()
    public String getEmail3() {
        return tableState.getFieldValue(table.field_email3, String.class);
    }
}
